# Generated by Django 5.0.3 on 2024-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utibuapp', '0002_tags_alter_product_description_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HIV', 'HIV'), ('DIABETES', 'DIABETES'), ('HYPERTENSION', 'HYPERTENSION')], max_length=200, null=True),
        ),
    ]
